apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: avp-v1
spec:
  allowConcurrency: true

  # tell ArgoCD “if you see any *.yaml under the repo root, invoke me”
  discover:
    fileName: "*.yaml"

  generate:
    command:
      - /usr/local/bin/argocd-vault-plugin
    args:
      - generate
      - .                   # the “path” argument
      - -c                  # short flag for --config-path
      - /home/argocd/cmp-server/config/vault-config.yaml

  provideGitCreds: true
  preserveFileMode: false
