apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: avp-v1
spec:
  allowConcurrency: true
  discover:
    fileName: "*.yaml"
  generate:
    command:
      - /usr/local/bin/argocd-vault-plugin
    args:
      - generate
      - .
      - --config-path=/home/argocd/cmp-server/config/vault-config.yaml
  provideGitCreds: true
  preserveFileMode: false